import requests
import sys
import os

# Get the file name from command line argument
file_name = sys.argv[1]

# Get the API key from environment variable
api_token = os.environ.get('DEFECTDOJO_API_KEY')
if not api_token:
    print("API token not set. Set the DEFECTDOJO_API_KEY environment variable.")
    sys.exit(1)

# Define headers for the request
headers = {
    'Authorization': f'Token {api_token}' 
}

# URL for the DefectDojo API endpoint
# We utilized ngrok to expose our local DefectDojo instance to the internet
# This URL is a temporary URL generated by ngrok.

url = 'https://a32e-24-11-167-243.ngrok-free.app/api/v2/import-scan/'

# Determine scan type based on file name
if file_name == 'gitleaks.json':
    scan_type = 'Gitleaks Scan'
elif file_name == 'semgrep.json':
    scan_type = 'Semgrep JSON Report'
elif file_name == 'njsscan.sarif':
    scan_type = 'SARIF'
else:
    print(f"Unknown file type: {file_name}")
    sys.exit(1)

# Define scan configuration
data = {
    'scan_type': scan_type,
    'active': True,
    'verified': True,
    'minimum_severity': 'Low',
    'engagement': 2
}

# Open the file in binary mode

files = {
'file': open(file_name, 'rb')
}

response = requests.post(url, headers=headers, data=data, files=files)
# Check if the request was successful
if response.status_code == 201:
    print('Scan uploaded successfully.')
else:
    print('Failed to upload scan. Status code:', response.status_code)
    print(f"'Response:', {response.content}")
